### PR TITLE
V/abs val cacti

### PR DESCRIPTION
**Pull request by fazerlicourice7**
this is no Bueno. 
Still need to verify the grad calculations to see if those are wrong as well. But we need to figure out what to do about this.

absolute_validation

### CODE REVIEW

**Comment by fazerlicourice7** [comment]
Partial results for grad validation.
If it says 0 it means basically no correlation between the two gradients.
If it doesn't have a number, then it means there is actually no dependence. 
base_cache_45_grad_similarity

**Comment by fazerlicourice7** [comment]
Ok update. I was wrong about how bad the absolute validation was. Here is an updated plot.
The issue is with the cacti_python library maintaining state.

**Comment by fazerlicourice7** [comment]
But the gradients are still bad.

**Comment by fazerlicourice7** [comment]
mem_cache_32_grad_similarity

**Review by dwoen — APPROVED** [review]
As long as we want 90nm as the limit, this is good.

**Pull request merged**
